apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-journal-authentication
  namespace: trading-journal
data:
  ADMIN_EMAIL: "<ADMIN_EMAIL>"
  EMAIL_HOST: "<SMTP_HOST>"
  EMAIL_USERNAME: "<SMTP_USER>"
  EMAIL_PORT: "<SMTP_PORT:587>"
  DATASOURCE_URL: "jdbc:postgresql://<HOST>:<PORT>/<DATA_BASE_NAME>"
  DATASOURCE_USERNAME: "<DATASOURCE_USER>"
  JWT_ACCESS_TOKEN_EXPIRATION: "<SECONDS:3600>"
  JWT_AUDIENCE: "<AUDIENCE>>"
  JWT_ISSUER: "<ISSUER>"
  JWT_REFRESH_TOKEN_EXPIRATION: "<SECONDS:86400>"
  WEB_APP_URL: "<FRONT_END_HOST>"
  JWT_PRIVATE_KEY: '<JWT_PRIVATE_KEY>'
  JWT_PUBLIC_KEY: '<JWT_PUBLIC_KEY>'

