apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-journal-authentication
  namespace: trading-journal
  labels:
    app: trading-journal-authentication
spec:
  selector:
    matchLabels:
      app: trading-journal-authentication
  replicas: 1
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: trading-journal-authentication
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/prometheus'
    spec:
      volumes:
        - name: trading-journal-private-key
          configMap:
            name: trading-journal-private-key
        - name: trading-journal-public-key
          configMap:
            name: trading-journal-public-key
      terminationGracePeriodSeconds: 1
      containers:
        - name: trading-journal-authentication
          image: allanweber/trading-journal-authentication:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            limits:
              cpu: '0.5'
              memory: '512Mi'
            requests:
              cpu: '0.5'
              memory: '512Mi'
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trading-journal-private-key
              readOnly: false
              mountPath: '/etc/ssl/certs/private_key.pem'
              subPath: private_key.pem
            - name: trading-journal-public-key
              readOnly: false
              mountPath: '/etc/ssl/certs/public_key.pem'
              subPath: public_key.pem
          env:
            - name: ES_JAVA_OPTS
              value: '-Xmx512m -Xms512m'
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trading-journal-authentication
                  key: EMAIL_PASSWORD
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trading-journal-authentication
                  key: DATASOURCE_PASSWORD
          envFrom:
            - configMapRef:
                name: trading-journal-authentication
